language: cpp

script-anchors:
  - &script-documentation
    - cd $TRAVIS_BUILD_DIR
    - make docs
    - cp -r .circleci $TRAVIS_BUILD_DIR/docs/documentation/html/

  - &script-macOS
    - brew install ninja
    - CONFIG=Debug make

matrix:
  include:
    - os: osx
      osx_image: xcode11
      script: *script-macOS

    - os: linux
      dist: bionic
      branches:
        only:
          - master
      addons:
        apt:
          packages:
            - doxygen
            - texlive
            - graphviz
      script: *script-documentation
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: $TRAVIS_BUILD_DIR/docs/documentation/html
        github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master
