name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake mesa-utils freeglut3-dev gcovr lcov

      - name: Install conan
        run: |
          pip3 install conan
          conan config init
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update conf.tools.system.package_manager:mode=install default
          conan profile update conf.tools.system.package_manager:sudo=True default

      - name: Run coverage build
        run: make coverage-xml coverage-html

      - uses: codecov/codecov-action@v3
        with:
          files: ./cmake-build-coverage/coverage.xml
          fail_ci_if_error: true
