name: Emscripten

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  emcc:
    name: EMCC
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake

      - name: Install conan
        run: |
          pip3 install --force-reinstall "conan==1.61.0"
          conan config init
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: Build dependencies
        run: >
          conan install
          -if build
          --build=missing
          -pr:b=default
          -pr:h="profiles/emscripten.profile"
          -s compiler.cppstd=20
          -s build_type=Release
          .

      - name: Build & Test
        run: conan build -bf build .
