name: Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cl:
    name: CL
    runs-on: windows-2022
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install ninja
        run: choco install ninja

      - name: Install conan
        run: |
          pip3 install --force-reinstall "conan==1.61.0"
          conan config init

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Configure OpenGL (modern) - Release
        run: >
          cmake -S.
          -B cmake-build-modern
          -G "Ninja"
          -D CMAKE_BUILD_TYPE=Release
          -D CMAKE_UNITY_BUILD=ON
          -D MOCI_API_OPENGL_MODERN=ON
          -D MOCI_API_OPENGL_LEGACY=OFF

      - name: Build OpenGL (modern) - Release
        run: cmake --build cmake-build-modern --config Release

      - name: Test OpenGL (modern) - Release
        run: ctest --test-dir cmake-build-modern -C Release --output-on-failure

      - name: Configure OpenGL (legacy) - Release
        run: >
          cmake -S.
          -B cmake-build-legacy
          -G "Ninja"
          -D CMAKE_BUILD_TYPE=Release
          -D CMAKE_UNITY_BUILD=ON
          -D MOCI_API_OPENGL_MODERN=OFF
          -D MOCI_API_OPENGL_LEGACY=ON

      - name: Build OpenGL (legacy) - Release
        run: cmake --build cmake-build-legacy --config Release

      - name: Test OpenGL (legacy) - Release
        run: ctest --test-dir cmake-build-legacy -C Release --output-on-failure
